export default [
  {
    "StadiumID": 1,
    "Active": true,
    "Name": "Capital One Arena",
    "Address": "601 F St. N.W.",
    "City": "Washington",
    "State": "DC",
    "Zip": "20004",
    "Country": "USA",
    "Capacity": 20290,
    "GeoLat": 38.898056,
    "GeoLong": -77.020833
  },
  {
    "StadiumID": 2,
    "Active": true,
    "Name": "Spectrum Center",
    "Address": "330 E. Trade St.",
    "City": "Charlotte",
    "State": "NC",
    "Zip": "28202",
    "Country": "USA",
    "Capacity": 19026,
    "GeoLat": 35.225,
    "GeoLong": -80.839167
  },
  {
    "StadiumID": 3,
    "Active": true,
    "Name": "State Farm Arena",
    "Address": "1 State Farm Drive",
    "City": "Atlanta",
    "State": "GA",
    "Zip": "30303",
    "Country": "USA",
    "Capacity": 18118,
    "GeoLat": 33.757222,
    "GeoLong": -84.396389
  },
  {
    "StadiumID": 4,
    "Active": true,
    "Name": "Kaseya Center",
    "Address": "601 Biscayne Blvd.",
    "City": "Miami",
    "State": "FL",
    "Zip": "33132",
    "Country": "USA",
    "Capacity": 19600,
    "GeoLat": 25.781389,
    "GeoLong": -80.188056
  },
  {
    "StadiumID": 5,
    "Active": true,
    "Name": "Amway Center",
    "Address": "400 W. Church St.",
    "City": "Orlando",
    "State": "FL",
    "Zip": "32801",
    "Country": "USA",
    "Capacity": 18846,
    "GeoLat": 28.539167,
    "GeoLong": -81.383611
  },
  {
    "StadiumID": 6,
    "Active": true,
    "Name": "Madison Square Garden",
    "Address": "Four Pennsylvania Plaza",
    "City": "New York",
    "State": "NY",
    "Zip": "10001",
    "Country": "USA",
    "Capacity": 19812,
    "GeoLat": 40.750556,
    "GeoLong": -73.993611
  },
  {
    "StadiumID": 7,
    "Active": true,
    "Name": "Wells Fargo Center",
    "Address": "3601 S. Broad St.",
    "City": "Philadelphia",
    "State": "PA",
    "Zip": "19148",
    "Country": "USA",
    "Capacity": 20328,
    "GeoLat": 39.901111,
    "GeoLong": -75.171944
  },
  {
    "StadiumID": 8,
    "Active": true,
    "Name": "Barclays Center",
    "Address": "620 Atlantic Ave.",
    "City": "Brooklyn",
    "State": "NY",
    "Zip": "11217",
    "Country": "USA",
    "Capacity": 18200,
    "GeoLat": 40.682661,
    "GeoLong": -73.975225
  },
  {
    "StadiumID": 9,
    "Active": true,
    "Name": "TD Garden",
    "Address": "100 Legends Way",
    "City": "Boston",
    "State": "MA",
    "Zip": "2114",
    "Country": "USA",
    "Capacity": 17565,
    "GeoLat": 42.366303,
    "GeoLong": -71.062228
  },
  {
    "StadiumID": 10,
    "Active": true,
    "Name": "Scotiabank Arena",
    "Address": "40 Bay St.",
    "City": "Toronto",
    "State": "ON",
    "Zip": "M5J 2X2",
    "Country": "CAN",
    "Capacity": 19800,
    "GeoLat": 43.643333,
    "GeoLong": -79.379167
  },
  {
    "StadiumID": 11,
    "Active": true,
    "Name": "United Center",
    "Address": "1901 W. Madison St.",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60612",
    "Country": "USA",
    "Capacity": 20917,
    "GeoLat": 41.880556,
    "GeoLong": -87.674167
  },
  {
    "StadiumID": 12,
    "Active": true,
    "Name": "Rocket Mortgage FieldHouse",
    "Address": "One Center Court",
    "City": "Cleveland",
    "State": "OH",
    "Zip": "44115",
    "Country": "USA",
    "Capacity": 20562,
    "GeoLat": 41.496389,
    "GeoLong": -81.688056
  },
  {
    "StadiumID": 13,
    "Active": true,
    "Name": "Gainbridge Fieldhouse",
    "Address": "125 S. Pennsylvania St.",
    "City": "Indianapolis",
    "State": "IN",
    "Zip": "46204",
    "Country": "USA",
    "Capacity": 20000,
    "GeoLat": 39.763889,
    "GeoLong": -86.155556
  },
  {
    "StadiumID": 14,
    "Active": true,
    "Name": "Little Caesars Arena",
    "Address": "2645 Woodward Ave",
    "City": "Detroit",
    "State": "MI",
    "Zip": "48201",
    "Country": "USA",
    "Capacity": 20491,
    "GeoLat": 42.551262,
    "GeoLong": -83.217862
  },
  {
    "StadiumID": 15,
    "Active": true,
    "Name": "Fiserv Forum",
    "Address": "1001 N Fourth St.",
    "City": "Milwaukee",
    "State": "WI",
    "Zip": "53203",
    "Country": "USA",
    "Capacity": 19000,
    "GeoLat": 43.043611,
    "GeoLong": -87.916944
  },
  {
    "StadiumID": 16,
    "Active": true,
    "Name": "Target Center",
    "Address": "600 First Ave. North",
    "City": "Minneapolis",
    "State": "MN",
    "Zip": "55403",
    "Country": "USA",
    "Capacity": 19356,
    "GeoLat": 44.979444,
    "GeoLong": -93.276111
  },
  {
    "StadiumID": 17,
    "Active": true,
    "Name": "Delta Center",
    "Address": "301 W. South Temple St.",
    "City": "Salt Lake City",
    "State": "UT",
    "Zip": "84101",
    "Country": "USA",
    "Capacity": 19911,
    "GeoLat": 40.768333,
    "GeoLong": -111.901111
  },
  {
    "StadiumID": 18,
    "Active": true,
    "Name": "Paycom Center",
    "Address": "100 W. Reno Ave.",
    "City": "Oklahoma City",
    "State": "OK",
    "Zip": "73102",
    "Country": "USA",
    "Capacity": 18203,
    "GeoLat": 35.463333,
    "GeoLong": -97.515
  },
  {
    "StadiumID": 19,
    "Active": true,
    "Name": "Moda Center",
    "Address": "1 Center Court",
    "City": "Portland",
    "State": "OR",
    "Zip": "97227",
    "Country": "USA",
    "Capacity": 19980,
    "GeoLat": 45.531667,
    "GeoLong": -122.666667
  },
  {
    "StadiumID": 20,
    "Active": true,
    "Name": "Ball Arena",
    "Address": "1000 Chopper Circle",
    "City": "Denver",
    "State": "CO",
    "Zip": "80204",
    "Country": "USA",
    "Capacity": 19155,
    "GeoLat": 39.748611,
    "GeoLong": -105.0075
  },
  {
    "StadiumID": 21,
    "Active": true,
    "Name": "FedExForum",
    "Address": "191 Beale St.",
    "City": "Memphis",
    "State": "TN",
    "Zip": "38103",
    "Country": "USA",
    "Capacity": 18119,
    "GeoLat": 35.138333,
    "GeoLong": -90.050556
  },
  {
    "StadiumID": 22,
    "Active": true,
    "Name": "Toyota Center",
    "Address": "1510 Polk St.",
    "City": "Houston",
    "State": "TX",
    "Zip": "77002",
    "Country": "USA",
    "Capacity": 18043,
    "GeoLat": 29.750833,
    "GeoLong": -95.362222
  },
  {
    "StadiumID": 23,
    "Active": true,
    "Name": "Smoothie King Center",
    "Address": "1501 Girod St.",
    "City": "New Orleans",
    "State": "LA",
    "Zip": "70113",
    "Country": "USA",
    "Capacity": 17188,
    "GeoLat": 29.948889,
    "GeoLong": -90.081944
  },
  {
    "StadiumID": 24,
    "Active": true,
    "Name": "Frost Bank Center",
    "Address": "One AT&T Center Parkway",
    "City": "San Antonio",
    "State": "TX",
    "Zip": "78219",
    "Country": "USA",
    "Capacity": 18581,
    "GeoLat": 29.426944,
    "GeoLong": -98.4375
  },
  {
    "StadiumID": 25,
    "Active": true,
    "Name": "American Airlines Center",
    "Address": "2500 Victory Ave.",
    "City": "Dallas",
    "State": "TX",
    "Zip": "75219",
    "Country": "USA",
    "Capacity": 19200,
    "GeoLat": 32.790556,
    "GeoLong": -96.810278
  },
  {
    "StadiumID": 26,
    "Active": true,
    "Name": "Oakland Arena",
    "Address": "7000 Coliseum Way",
    "City": "Oakland",
    "State": "CA",
    "Zip": "94621",
    "Country": "USA",
    "Capacity": 18064,
    "GeoLat": 37.7681,
    "GeoLong": -122.3875
  },
  {
    "StadiumID": 27,
    "Active": true,
    "Name": "Crypto.com Arena",
    "Address": "1111 S. Figueroa St.",
    "City": "Los Angeles",
    "State": "CA",
    "Zip": "90015",
    "Country": "USA",
    "Capacity": 18997,
    "GeoLat": 34.043056,
    "GeoLong": -118.267222
  },
  {
    "StadiumID": 28,
    "Active": true,
    "Name": "Footprint Center",
    "Address": "201 E. Jefferson St.",
    "City": "Phoenix",
    "State": "AZ",
    "Zip": "85004",
    "Country": "USA",
    "Capacity": 18422,
    "GeoLat": 33.445833,
    "GeoLong": -112.071389
  },
  {
    "StadiumID": 29,
    "Active": true,
    "Name": "Golden 1 Center",
    "Address": "One Sports Parkway",
    "City": "Sacramento",
    "State": "CA",
    "Zip": "95834",
    "Country": "USA",
    "Capacity": 17317,
    "GeoLat": 38.649167,
    "GeoLong": -121.518056
  },
  {
    "StadiumID": 30,
    "Active": true,
    "Name": "Mercedes-Benz Arena",
    "Address": "Expo Ave.",
    "City": "Shanghai",
    "State": "PVG",
    "Zip": "310115",
    "Country": "CHN",
    "Capacity": 18000,
    "GeoLat": 31.151592,
    "GeoLong": 121.798698
  },
  {
    "StadiumID": 31,
    "Active": true,
    "Name": "Key Arena",
    "Address": "305 Harrison St.",
    "City": "Seattle",
    "State": "WA",
    "Zip": "98109",
    "Country": "USA",
    "Capacity": 17072,
    "GeoLat": 47.621969,
    "GeoLong": -122.329108
  },
  {
    "StadiumID": 32,
    "Active": true,
    "Name": "Dean E. Smith Center",
    "Address": null,
    "City": "Chapel Hill",
    "State": null,
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 33,
    "Active": true,
    "Name": "Valley View Casino Center",
    "Address": null,
    "City": "San Diego",
    "State": null,
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 34,
    "Active": true,
    "Name": "McCamish Pavilion",
    "Address": null,
    "City": "Atlanta",
    "State": null,
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 35,
    "Active": true,
    "Name": "Legacy Arena at BJCC",
    "Address": "2100 Richard Arrington Jr. Blvd ",
    "City": "Birmingham",
    "State": "AL",
    "Zip": "35203",
    "Country": "USA",
    "Capacity": 19000,
    "GeoLat": 33.526969,
    "GeoLong": -86.809553
  },
  {
    "StadiumID": 36,
    "Active": true,
    "Name": "Honda Center",
    "Address": "2695 E. Katella Ave.",
    "City": "Anaheim",
    "State": "CA",
    "Zip": "92806",
    "Country": "USA",
    "Capacity": 18336,
    "GeoLat": 33.807778,
    "GeoLong": -117.876667
  },
  {
    "StadiumID": 37,
    "Active": true,
    "Name": "BOK Center",
    "Address": "200 South Denver Ave.",
    "City": "Tulsa",
    "State": "OK",
    "Zip": "74103",
    "Country": "USA",
    "Capacity": 19199,
    "GeoLat": 36.121663,
    "GeoLong": -95.940621
  },
  {
    "StadiumID": 38,
    "Active": true,
    "Name": "Hilton Coliseum",
    "Address": "1700 Center Dr.",
    "City": "Ames",
    "State": "IA",
    "Zip": "50011",
    "Country": "USA",
    "Capacity": 14356,
    "GeoLat": 42.025326,
    "GeoLong": -93.633792
  },
  {
    "StadiumID": 41,
    "Active": true,
    "Name": "Shenzhen Universiade Center",
    "Address": "3001 Longxiang Ave.",
    "City": "Shenzhen",
    "State": "",
    "Zip": "518115",
    "Country": "CHN",
    "Capacity": 60334,
    "GeoLat": 22.675843,
    "GeoLong": 113.817939
  },
  {
    "StadiumID": 42,
    "Active": true,
    "Name": "Bell Centre",
    "Address": "1909 Avenue des Canadiens-de-Montreal",
    "City": "Montreal",
    "State": "QC",
    "Zip": "H3B 5E8",
    "Country": "CAN",
    "Capacity": 21273,
    "GeoLat": 45.496111,
    "GeoLong": -73.569444
  },
  {
    "StadiumID": 43,
    "Active": true,
    "Name": "T-Mobile Arena",
    "Address": "3780 S. Las Vegas Blvd.",
    "City": "Las Vegas",
    "State": "NV",
    "Zip": "89158",
    "Country": "USA",
    "Capacity": 17500,
    "GeoLat": 36.102778,
    "GeoLong": -115.178333
  },
  {
    "StadiumID": 44,
    "Active": true,
    "Name": "Breslin Center",
    "Address": "534 Birch Road",
    "City": "East Lansing",
    "State": "MI",
    "Zip": "48824",
    "Country": "USA",
    "Capacity": 14859,
    "GeoLat": 42.737577,
    "GeoLong": -84.517733
  },
  {
    "StadiumID": 45,
    "Active": true,
    "Name": "SAP Center at San Jose",
    "Address": "525 W. Santa Clara St.",
    "City": "San Jose",
    "State": "CA",
    "Zip": "95113",
    "Country": "USA",
    "Capacity": 17562,
    "GeoLat": 37.332778,
    "GeoLong": -121.901111
  },
  {
    "StadiumID": 46,
    "Active": true,
    "Name": "Rogers Arena",
    "Address": "800 Griffiths Way",
    "City": "Vancouver",
    "State": "BC",
    "Zip": "V6B 6G1",
    "Country": "CAN",
    "Capacity": 18890,
    "GeoLat": 49.277778,
    "GeoLong": -123.108889
  },
  {
    "StadiumID": 48,
    "Active": true,
    "Name": "Mexico City Arena",
    "Address": "Av. de las Granjas 800",
    "City": "Mexico City",
    "State": "",
    "Zip": "02230",
    "Country": "Mexico",
    "Capacity": 22300,
    "GeoLat": 19.49328,
    "GeoLong": -99.173187
  },
  {
    "StadiumID": 49,
    "Active": true,
    "Name": "O2 ARENA",
    "Address": "Peninsula Square",
    "City": "London",
    "State": "",
    "Zip": "SE10 0DX",
    "Country": "UK",
    "Capacity": 20000,
    "GeoLat": 51.501796,
    "GeoLong": 0.00188
  },
  {
    "StadiumID": 51,
    "Active": true,
    "Name": "Chase Center",
    "Address": null,
    "City": "San Francisco",
    "State": "CA",
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 52,
    "Active": true,
    "Name": "Lawrence Joel Veterans Memorial Colesium",
    "Address": null,
    "City": "Winston-Salem",
    "State": "NC",
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 53,
    "Active": true,
    "Name": "Saitama Super Arena",
    "Address": null,
    "City": "Saitama City",
    "State": null,
    "Zip": null,
    "Country": "Japan",
    "Capacity": 35000,
    "GeoLat": 0,
    "GeoLong": 0
  },
  {
    "StadiumID": 54,
    "Active": true,
    "Name": "NSCI Dome",
    "Address": null,
    "City": "Mumbai",
    "State": null,
    "Zip": null,
    "Country": "India",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 55,
    "Active": true,
    "Name": "Stan Sheriff Center",
    "Address": null,
    "City": "Honolulu",
    "State": "HA",
    "Zip": null,
    "Country": "USA",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 56,
    "Active": true,
    "Name": "Accor Arena",
    "Address": "8 Boulevard de Bercy",
    "City": "Paris",
    "State": null,
    "Zip": null,
    "Country": "France",
    "Capacity": null,
    "GeoLat": 48.838653,
    "GeoLong": 2.3785
  },
  {
    "StadiumID": 91,
    "Active": true,
    "Name": "ESPN Wide World of Sports Complex",
    "Address": "700 S Victory Way",
    "City": "Reunion",
    "State": "FL",
    "Zip": "34747",
    "Country": "USA",
    "Capacity": null,
    "GeoLat": 28.337083,
    "GeoLong": -81.556
  },
  {
    "StadiumID": 94,
    "Active": true,
    "Name": "Arena Ciudad de Mexico",
    "Address": null,
    "City": "Mexico City",
    "State": null,
    "Zip": "02230",
    "Country": "Mexico",
    "Capacity": null,
    "GeoLat": null,
    "GeoLong": null
  },
  {
    "StadiumID": 95,
    "Active": true,
    "Name": "Amalie Arena",
    "Address": "401 Channelside Drive",
    "City": "Tampa",
    "State": "FL",
    "Zip": "33602",
    "Country": "USA",
    "Capacity": 20500,
    "GeoLat": 27.942778,
    "GeoLong": -82.451944
  },
  {
    "StadiumID": 96,
    "Active": true,
    "Name": "Bank of Oklahoma Center",
    "Address": "200 South Denver Avenue West",
    "City": "Tulsa",
    "State": "OK",
    "Zip": "74103",
    "Country": "USA",
    "Capacity": 17839,
    "GeoLat": 36.1483,
    "GeoLong": -95.9963
  },
  {
    "StadiumID": 97,
    "Active": true,
    "Name": "Toyota Arena",
    "Address": "4000 Ontario Center",
    "City": "Ontario",
    "State": "CA",
    "Zip": "91764",
    "Country": "USA",
    "Capacity": 11089,
    "GeoLat": 34.0685,
    "GeoLong": -117.5389
  },
  {
    "StadiumID": 98,
    "Active": true,
    "Name": "Etihad Arena",
    "Address": null,
    "City": "Yas Island",
    "State": null,
    "Zip": null,
    "Country": "Abu Dhabi",
    "Capacity": 18000,
    "GeoLat": 24.4603,
    "GeoLong": 54.604
  },
  {
    "StadiumID": 99,
    "Active": false,
    "Name": "Climate Pledge Arena",
    "Address": "305 Harrison St",
    "City": "Seattle",
    "State": "WA",
    "Zip": "98109",
    "Country": "USA",
    "Capacity": 17459,
    "GeoLat": 47.622,
    "GeoLong": -122.354
  },
  {
    "StadiumID": 100,
    "Active": false,
    "Name": "Alamodome",
    "Address": "100 Montana St",
    "City": "San Antonio",
    "State": "TX",
    "Zip": "78203",
    "Country": "USA",
    "Capacity": 20662,
    "GeoLat": 29.416944,
    "GeoLong": -98.478889
  },
  {
    "StadiumID": 101,
    "Active": false,
    "Name": "Moody Center",
    "Address": "2001 Robert Dedman Dr",
    "City": "Austin",
    "State": "TX",
    "Zip": "78712",
    "Country": "USA",
    "Capacity": 15000,
    "GeoLat": 30.280972,
    "GeoLong": -97.730472
  },
  {
    "StadiumID": 102,
    "Active": false,
    "Name": "Rogers Place",
    "Address": "10220 104 Avenue NW",
    "City": "Edmonton",
    "State": "AB",
    "Zip": null,
    "Country": "Canada",
    "Capacity": 19500,
    "GeoLat": 53.546944,
    "GeoLong": -113.497778
  },
  {
    "StadiumID": 103,
    "Active": false,
    "Name": "Greensboro Coliseum Fieldhouse",
    "Address": "1921 W Gate City Blvd",
    "City": "Greensboro",
    "State": "NC",
    "Zip": "27403",
    "Country": "USA",
    "Capacity": 23500,
    "GeoLat": 36.059722,
    "GeoLong": -79.825556
  },
  {
    "StadiumID": 104,
    "Active": true,
    "Name": "Gateway Center",
    "Address": "2330 Convention Center Concourse",
    "City": "College Park",
    "State": "GA",
    "Zip": "30337",
    "Country": "USA",
    "Capacity": 3500,
    "GeoLat": 33.6468,
    "GeoLong": 84.459616
  },
  {
    "StadiumID": 105,
    "Active": true,
    "Name": "Acrisure Arena",
    "Address": "75702 Varner Road",
    "City": "Palm Desert",
    "State": "CA",
    "Zip": "92211",
    "Country": "USA",
    "Capacity": 10815,
    "GeoLat": 33.77917,
    "GeoLong": -116.33889
  }
]