export default
[
    {
      "Acronym": "ATL",
      "Name": "Atlanta",
      "FullName": "Atlanta Hawks",
      "NickName": "Hawks",
      "Arena": "State Farm Arena",
      "Division": "Southeast",
      "Conference": "East",
      "City": "Atlanta, Georgia",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "BOS",
      "Name": "Boston",
      "FullName": "Boston Celtics",
      "NickName": "Celtics",
      "Arena": "TD Garden",
      "Division": "Atlantic",
      "Conference": "East",
      "City": "Boston, Massachusetts",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "BKN",
      "Name": "Brooklyn",
      "FullName": "Brooklyn Nets",
      "NickName": "Nets",
      "Arena": "Barclays Center",
      "Division": "Atlantic",
      "Conference": "East",
      "City": "Brooklyn, New York",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "CHA",
      "Name": "Charlotte",
      "FullName": "Charlotte Hornets",
      "NickName": "Hornets",
      "Arena": "Spectrum Center",
      "Division": "Southeast",
      "Conference": "East",
      "City": "Charlotte, North Carolina",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "CHI",
      "Name": "Chicago",
      "FullName": "Chicago Bulls",
      "NickName": "Bulls",
      "Arena": "United Center",
      "Division": "Central",
      "Conference": "East",
      "City": "Chicago, Illinois",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "CLE",
      "Name": "Cleveland",
      "FullName": "Cleveland Cavaliers",
      "NickName": "Cavaliers",
      "Arena": "Rocket Mortgage FieldHouse",
      "Division": "Central",
      "Conference": "East",
      "City": "Cleveland, Ohio",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "DAL",
      "Name": "Dallas",
      "FullName": "Dallas Mavericks",
      "NickName": "Mavericks",
      "Arena": "American Airlines Center",
      "Division": "Southwest",
      "Conference": "West",
      "City": "Dallas, Texas",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "DEN",
      "Name": "Denver",
      "FullName": "Denver Nuggets",
      "NickName": "Nuggets",
      "Arena": "Ball Arena",
      "Division": "Northwest",
      "Conference": "West",
      "City": "Denver, Colorado",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "DET",
      "Name": "Detroit",
      "FullName": "Detroit Pistons",
      "NickName": "Pistons",
      "Arena": "Little Caesars Arena",
      "Division": "Central",
      "Conference": "East",
      "City": "Detroit, Michigan",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "GSW",
      "Name": "Golden State",
      "FullName": "Golden State Warriors",
      "NickName": "Warriors",
      "Arena": "Chase Center",
      "Division": "Pacific",
      "Conference": "West",
      "City": "San Francisco, California",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "HOU",
      "Name": "Houston",
      "FullName": "Houston Rockets",
      "NickName": "Rockets",
      "Arena": "Toyota Center",
      "Division": "Southwest",
      "Conference": "West",
      "City": "Houston, Texas",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "IND",
      "Name": "Indiana",
      "FullName": "Indiana Pacers",
      "NickName": "Pacers",
      "Arena": "Bankers Life Fieldhouse",
      "Division": "Central",
      "Conference": "East",
      "City": "Indianapolis, Indiana",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "LAC",
      "Name": "LA Clippers",
      "FullName": "Los Angeles Clippers",
      "NickName": "Clippers",
      "Arena": "Staples Center",
      "Division": "Pacific",
      "Conference": "West",
      "City": "Los Angeles, California",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "LAL",
      "Name": "LA Lakers",
      "FullName": "Los Angeles Lakers",
      "NickName": "Lakers",
      "Arena": "Staples Center",
      "Division": "Pacific",
      "Conference": "West",
      "City": "Los Angeles, California",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "MEM",
      "Name": "Memphis",
      "FullName": "Memphis Grizzlies",
      "NickName": "Grizzlies",
      "Arena": "FedExForum",
      "Division": "Southwest",
      "Conference": "West",
      "City": "Memphis, Tennessee",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "MIA",
      "Name": "Miami",
      "FullName": "Miami Heat",
      "NickName": "Heat",
      "Arena": "American Airlines Arena",
      "Division": "Southeast",
      "Conference": "East",
      "City": "Miami, Florida",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "MIL",
      "Name": "Milwaukee",
      "FullName": "Milwaukee Bucks",
      "NickName": "Bucks",
      "Arena": "Fiserv Forum",
      "Division": "Central",
      "Conference": "East",
      "City": "Milwaukee, Wisconsin",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "MIN",
      "Name": "Minnesota",
      "FullName": "Minnesota Timberwolves",
      "NickName": "Timberwolves",
      "Arena": "Target Center",
      "Division": "Northwest",
      "Conference": "West",
      "City": "Minneapolis, Minnesota",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "NOP",
      "Name": "New Orleans",
      "FullName": "New Orleans Pelicans",
      "NickName": "Pelicans",
      "Arena": "Smoothie King Center",
      "Division": "Southwest",
      "Conference": "West",
      "City": "New Orleans, Louisiana",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "NYK",
      "Name": "New York",
      "FullName": "New York Knicks",
      "NickName": "Knicks",
      "Arena": "Madison Square Garden",
      "Division": "Atlantic",
      "Conference": "East",
      "City": "New York City, New York",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "OKC",
      "Name": "Oklahoma City",
      "FullName": "Oklahoma City Thunder",
      "NickName": "Thunder",
      "Arena": "Chesapeake Energy Arena",
      "Division": "Northwest",
      "Conference": "West",
      "City": "Oklahoma City, Oklahoma",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "ORL",
      "Name": "Orlando",
      "FullName": "Orlando Magic",
      "NickName": "Magic",
      "Arena": "Amway Center",
      "Division": "Southeast",
      "Conference": "East",
      "City": "Orlando, Florida",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "PHI",
      "Name": "Philadelphia",
      "FullName": "Philadelphia 76ers",
      "NickName": "76ers",
      "Arena": "Wells Fargo Center",
      "Division": "Atlantic",
      "Conference": "East",
      "City": "Philadelphia, Pennsylvania",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "PHO",
      "Name": "Phoenix",
      "FullName": "Phoenix Suns",
      "NickName": "Suns",
      "Arena": "PHX Arena",
      "Division": "Pacific",
      "Conference": "West",
      "City": "Phoenix, Arizona",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "POR",
      "Name": "Portland",
      "FullName": "Portland Trail Blazers",
      "NickName": "Trail Blazers",
      "Arena": "Moda Center",
      "Division": "Northwest",
      "Conference": "West",
      "City": "Portland, Oregon",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "SAC",
      "Name": "Sacramento",
      "FullName": "Sacramento Kings",
      "NickName": "Kings",
      "Arena": "Golden 1 Center",
      "Division": "Pacific",
      "Conference": "West",
      "City": "Sacramento, California",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "SAN",
      "Name": "San Antonio",
      "FullName": "San Antonio Spurs",
      "NickName": "Spurs",
      "Arena": "AT&T Center",
      "Division": "Southwest",
      "Conference": "West",
      "City": "San Antonio, Texas",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "TOR",
      "Name": "Toronto",
      "FullName": "Toronto Raptors",
      "NickName": "Raptors",
      "Arena": "Amalie Arena",
      "Division": "Atlantic",
      "Conference": "East",
      "City": "Tampa, Florida",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "UTA",
      "Name": "Utah",
      "FullName": "Utah Jazz",
      "NickName": "Jazz",
      "Arena": "Vivint Smart Home Arena",
      "Division": "Northwest",
      "Conference": "West",
      "City": "Salt Lake City, Utah",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    },
    {
      "Acronym": "WAS",
      "Name": "Washington",
      "FullName": "Washington Wizards",
      "NickName": "Wizards",
      "Arena": "Capital One Arena",
      "Division": "Southeast",
      "Conference": "East",
      "City": "Washington, D.C.",
      "RoadGames": 41,
      "HomeGames": 41,
      "TotalGames": 82
    }
  ]

